name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change ici si ta branche principale est différente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Déployer via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/portail-lcdd
            git pull origin main
            npm install --production
            npm run build
            pm2 restart all
