name: Deploy to VPS

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Déployer via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/portail-lcdd
            git pull origin main
            cd front
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npm run build
            cd ..
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart all
            sudo systemctl restart nginx
